FROM golang:1.24-alpine AS builder 
WORKDIR /app 

COPY go.mod go.sum ./

RUN go mod download 
COPY . .


RUN CGO_ENABLED=0 GOOS=linux go build -o /agent-bin ./cmd/agent 

FROM gcr.io/distroless/static-debian12 
WORKDIR / 
COPY --from=builder /agent-bin /agent


ENTRYPOINT ["/agent"] 
