FROM golang:1.24-alpine AS builder 

WORKDIR /app 

COPY go.mod go.sum ./ 
RUN go mod download 

COPY . . 

RUN CGO_ENABLED=0 GOOS=linux go build -o  /server-bin ./cmd/server 


FROM gcr.io/distroless/base-debian12

WORKDIR / 

COPY --from=builder /server-bin /server

EXPOSE 8080 

ENTRYPOINT ["/server"] 
